### ISSUE TITLE
MAC bug

### ISSUE THREAD

**Issue by lianfeng30** [fengxuangit/Fox-scan#2]
File "views.py", line 18, in <module>
    mysql = MySQLHander()
  File "/XAMPP/xamppfiles/htdocs/foxscan/libs/models.py", line 14, in __init__
    password = xml.GetElementByName('mysql/password').strip()
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by fengxuangit** [comment]
可能是你的mysql  password为空导致的，谢谢你的提醒。我之后会修复。

**Comment by lianfeng30** [comment]
是的 我root的密码是空

**Comment by lianfeng30** [comment]
期待尽快改下 感谢

**Comment by fengxuangit** [comment]
嗯嗯 好的

**Comment by fengxuangit** [comment]
已经修复路径报错问题 [Merge branch 'bugfix/patherror'](https://github.com/fengxuangit/Fox-scan/commit/7021f31eb3af80ec96348e0fa7ac5aee284db6cd)
