### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by jhhd88** [fengxuangit/Fox-scan#3]
E:\tools\Fox-scan>views.py
Traceback (most recent call last):
  File "E:\tools\Fox-scan\views.py", line 10, in <module>
    from libs.action import SqlMapAction,Spider_Handle,Save_Success_Target
  File "E:\tools\Fox-scan\libs\action.py", line 16, in <module>
    from models import MySQLHander
  File "E:\tools\Fox-scan\libs\models.py", line 5, in <module>
    import MySQLdb
  File "C:\Python27\lib\site-packages\MySQLdb\__init__.py", line 19, in <module>
    import _mysql
ImportError: DLL load failed: %1 ������Ч�� Win32 Ӧ�ó���

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

说明里还少了个依赖库ipdb

**Comment by lianfeng30** [comment]
自己pip install ipdb安装下即可

**Comment by fengxuangit** [comment]
不好意思 ，我都快忘记ipdb是第三方库了。我下个版本会修复

**Comment by jhhd88** [comment]
这是安装完所有依赖以后报的错.IPDB我已经装过了.

**Comment by fengxuangit** [comment]
这个可能是你MySQLdb没有安装好的 原因？  可以尝试在Linux下安装运行

**Comment by jhhd88** [comment]
换成了python64就能解决上面的报错,可是,下面还是报错.


E:\tools\Fox-scan>views.py
Traceback (most recent call last):
  File "E:\tools\Fox-scan\views.py", line 18, in <module>
    mysql = MySQLHander()
  File "E:\tools\Fox-scan\libs\models.py", line 11, in __init__
    xml = XMLDOM()
  File "E:\tools\Fox-scan\libs\func.py", line 40, in __init__
    xml = ET.parse("{0}/config.xml".format(getrootpath()))
  File "<string>", line 62, in parse
  File "<string>", line 26, in parse
IOError: [Errno 2] No such file or directory: 'E:\\tools\\Fox-scan\\lib/config.xml'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by fengxuangit** [comment]
哦  好吧  我这是路径分隔符没有考虑到windows的情况 你可以直接吧 `ET.parse("{0}/config.xml"` 改为 `ET.parse("{0}\config.xml"` 谢谢。我会修复的

**Comment by fengxuangit** [comment]
已经修复 [Merge branch 'bugfix/patherror'](https://github.com/fengxuangit/Fox-scan/commit/7021f31eb3af80ec96348e0fa7ac5aee284db6cd)
