### ISSUE TITLE
不支持TLS/https, Socks5，给你个建议

### ISSUE THREAD

**Issue by ring04h** [fengxuangit/Fox-scan#4]
基于mitmproxy，支持HTTP/HTTPS, Socks5的代理，可以使用plugins保存到数据库
https://github.com/ring04h/wyproxy

**Comment by lianfeng30** [comment]
楼上是猪哥 哇哈哈哈

**Comment by fengxuangit** [comment]
哦 谢谢

**Comment by hustlibraco** [comment]
我也做了个类似被动扫描器，也是采用mitmproxy来支持https，哈哈！

**Comment by fengxuangit** [comment]
https://github.com/fengxuangit/Fox-scan/pull/10
