### ISSUE TITLE
Cannot import foxscan.sql to Kali Linux 2016.2

### ISSUE THREAD

**Issue by samiux** [fengxuangit/Fox-scan#7]
I cannot import foxscan.sql to Kali Linux 2016.2.  After running source foxscan.sql inside mysql, the foxscan database is empty.

**Comment by fengxuangit** [comment]
Of it's empty,because you don't have any operations, you should start scan task,then the database will be some stuff here

**Comment by samiux** [comment]
There is no tables in foxscan database.

**Comment by fengxuangit** [comment]
it's impossible,look at the foxscan.sql  file , There are a lot of `CREATE TABLE ` command, check the mysql configure, If you still have this problem, you can create table yourself.

**Comment by samiux** [comment]
I wonder you did not test it in Kali Linux or other Linux distros.

**Comment by Arthur-Geng** [comment]
It's just a database structure, so there is no data inside. As fengxuangit said, after you make once sql injection test with fox-scan, you will see the data. I already tried it on kali linux, it's working. 
1. check your setting.
2. if it's still not working, try reinstall mysql or any requirement.
