### ISSUE TITLE
http://127.0.0.1:5000/action/status

### ISSUE THREAD

**Issue by lianfeng30** [fengxuangit/Fox-scan#8]
http://127.0.0.1:5000/action/status
正确配置扫描后 这个页面提示：

Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by fengxuangit** [comment]
..........    是啊  我没有这个页面啊。本身就不存在这个页面啊。

**Comment by lianfeng30** [comment]
好吧

**Comment by lianfeng30** [comment]
把Task Status  指向：http://127.0.0.1:5000/action/showtask 这个链接挺好

**Comment by lianfeng30** [comment]
否则访问http://127.0.0.1:5000/action/showtask  就要手工输入

**Comment by fengxuangit** [comment]
好的 我之后会更新下

**Comment by fengxuangit** [comment]
已修复
